services:
  - type: web
    name: roadrage
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd server && gunicorn --worker-class eventlet -w 1 app:app
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.9
    autoDeploy: true 